version: '3'

services:
  fastapi:
    container_name: fastapi_delivery
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DOCKER_PORT}

volumes:
  postgres_data:
